In [88]:
import torch
from stochman import nnj

In [89]:
_batch_size = 7
_input_size = 3
_hidden_size = 2
_output_size = 2

input = torch.randn(_batch_size, _input_size)
input2 = torch.randn(_batch_size, _input_size)

In [90]:
model = nnj.Linear(_input_size, _output_size)

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _output_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [91]:
model = nnj.Tanh()

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [92]:
model = nnj.ReLU()

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [93]:
model = nnj.L2Norm()

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _input_size)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
#GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'input', diag_inp = False, diag_out = False)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = True)
GGN = model._jacobian_sandwich(input, output, tmp, wrt = 'weight', diag_inp = False, diag_out = False)


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _input_size) for _ in range(3)]
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

tmp = torch.ones(_batch_size, _input_size, _input_size)
#GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'input', diag_inp = True, diag_out = False)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = True)
GGN = model._jacobian_sandwich_multipoint(input, input2, output, output2, tmps, wrt = 'weight', diag_inp = True, diag_out = False)

In [94]:
layers = [nnj.Linear(_input_size, _hidden_size),
          nnj.Tanh(),
          nnj.Linear(_hidden_size, _hidden_size),
          nnj.ReLU(),
          nnj.Linear(_hidden_size, _output_size),
          nnj.L2Norm()
          ]
                        
model = nnj.Sequential(layers,
                  add_hooks = True
)

### test single input ###
output = model(input)

tmp = torch.ones(_batch_size, _output_size)
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = True, method = 'diagonal approx')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = True, method = 'diagonal approx')

tmp = torch.ones(_batch_size, _output_size, _output_size)
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'input', diag_inp = False, method = 'diagonal approx')
GGN = model._jacobian_sandwich(input, tmp, wrt = 'weight', diag_inp = False, method = 'diagonal approx')


### test double input ###
output = model(input)
output2 = model(input2)

tmps = [torch.ones(_batch_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'input', diag_inp = True, method = 'diagonal exact')
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'weight', diag_inp = True, method = 'diagonal exact')

tmps = [torch.ones(_batch_size, _output_size, _output_size) for _ in range(3)]
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'input', diag_inp = False, method = 'diagonal exact')
GGN = model._jacobian_sandwich_multipoint(input, input2, tmps, wrt = 'weight', diag_inp = False, method = 'diagonal exact')

# Check correctness

In [95]:
stoch_model = nnj.Sequential([nnj.Linear(_input_size, _hidden_size),
                              nnj.ReLU(),
                              nnj.Linear(_hidden_size, _output_size),
                              #nnj.Tanh(),
                              #nnj.L2Norm()
                              ],
                  add_hooks = True
)

In [96]:
from jax import numpy as jnp
import numpy as np

def Relu(x):
    return jnp.maximum(x, jnp.zeros_like(x)) # max(0,x)

def Tanh(x):
    return jnp.tanh(x)

def L2Norm(x):
    x = x.T / (jnp.linalg.norm(x, ord=2, axis=1) + 1e-6)
    return x.T

def LinearLayer(w, b, x):
    w = w.reshape(len(b), -1)
    out = jnp.dot(x, w.T) + b
    return out

def jax_model(weights, x):
    w1 = weights[ : _input_size*_hidden_size]
    b1 = weights[_input_size*_hidden_size : _input_size*_hidden_size + _hidden_size]
    x = LinearLayer(w1, b1, x)
    x = Relu(x)
    w2 = weights[_input_size*_hidden_size + _hidden_size : _input_size*_hidden_size + _hidden_size + _hidden_size*_output_size]
    b2 = weights[_input_size*_hidden_size + _hidden_size + _hidden_size*_output_size : ]
    x = LinearLayer(w2, b2, x)
    #x = Tanh(x)
    #x = L2Norm(x)
    return x

_weights_size = _input_size*_hidden_size + _hidden_size + _hidden_size*_output_size + _output_size
        

In [97]:
# set weights and input to be equal
weights = []
for row in stoch_model._modules_list[0].weight.detach().numpy():
    weights = np.concatenate((weights, row))
weights= np.concatenate((weights, stoch_model._modules_list[0].bias.detach().numpy()))
for row in stoch_model._modules_list[2].weight.detach().numpy():
    weights = np.concatenate((weights, row))
weights = np.concatenate((weights, stoch_model._modules_list[2].bias.detach().numpy()))

weights = jnp.array(weights)

print(_weights_size, len(weights))

stoch_input = torch.randn(_batch_size, _input_size)
jax_input = jnp.array(stoch_input.numpy())


14 14


In [98]:
jax_model(weights, jax_input)
jnp.linalg.norm(jax_model(weights, jax_input), ord=2, axis=1)

DeviceArray([0.20421657, 0.20092005, 0.25616267, 0.19053367, 0.27515504,
             0.43389547, 0.47147834], dtype=float32)

In [99]:
from jax import vjp

f = lambda weights: jax_model(weights, jax_input)
y, vjp_fun = vjp(f, weights)

e_i = jnp.zeros((_batch_size, _output_size))
e_i = e_i.at[0,0].set(1)
v_i = vjp_fun(e_i)
print(e_i)
print(v_i)

[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
(DeviceArray([ 0.01732158, -0.00982765,  0.05841227,  0.05973367,
             -0.03389077,  0.20143534, -0.16125771, -0.556099  ,
              0.22516842,  0.04504061,  0.        ,  0.        ,
              1.        ,  0.        ], dtype=float32),)


In [100]:
# tmp is the identity matrix, for each batch element
identity = []
for i in range(_output_size):
    e_i = jnp.zeros((_batch_size, _output_size))
    for b in range(_batch_size):
        e_i = e_i.at[b,i].set(1)
    identity.append(e_i)

rows_of_J = []
for row in identity:
    v_i = vjp_fun(row)
    rows_of_J.append(v_i[0])

rows_of_J = np.array(rows_of_J)
cols_of_J = rows_of_J.T
print(rows_of_J.shape)
print(cols_of_J.shape)

GGN_by_jax = jnp.dot(cols_of_J, rows_of_J)
print(GGN_by_jax.shape)

GGN_diagonal_by_jax = []
for w in range(_weights_size):
    GGN_diagonal_by_jax.append(GGN_by_jax[w][w])
GGN_diagonal_by_jax = jnp.array(GGN_diagonal_by_jax)
print(GGN_diagonal_by_jax.shape)

(2, 14)
(14, 2)
(14, 14)
(14,)


In [101]:
cols_of_J

array([[ 1.8967760e-01,  2.9476598e-01],
       [ 1.1912173e-01,  1.8511955e-01],
       [ 5.0805789e-01,  7.8954077e-01],
       [-6.7780918e-01, -4.6249384e-01],
       [-9.6540225e-01, -6.5872908e-01],
       [ 2.2896237e-03,  1.5622842e-03],
       [-6.4503086e-01, -1.0024017e+00],
       [-1.6682971e+00, -1.1383398e+00],
       [ 2.1613588e+00,  0.0000000e+00],
       [ 1.2079453e+00,  0.0000000e+00],
       [ 0.0000000e+00,  2.1613588e+00],
       [ 0.0000000e+00,  1.2079453e+00],
       [ 7.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  7.0000000e+00]], dtype=float32)

In [105]:
identity_diagonal = torch.ones(_batch_size, _output_size)
GGN_diagonal_by_stoch = stoch_model._jacobian_sandwich(input,
                                                       identity_diagonal, 
                                                       wrt = 'weight', 
                                                       diag_inp = True, 
                                                       method = 'diagonal exact')

identity = torch.zeros(_batch_size, _output_size, _output_size)
for i in range(_output_size):
    for b in range(_batch_size):
        identity[b][i][i] = 1
GGN_diagonal_by_stoch2 = stoch_model._jacobian_sandwich(input,
                                                       identity, 
                                                       wrt = 'weight', 
                                                       diag_inp = False, 
                                                       method = 'diagonal exact')

In [106]:
GGN_diagonal_by_jax

DeviceArray([1.22864574e-01, 4.84592356e-02, 8.81497443e-01,
             6.73325837e-01, 1.36592543e+00, 7.68310838e-06,
             1.42087400e+00, 4.07903242e+00, 4.67147207e+00,
             1.45913196e+00, 4.67147207e+00, 1.45913196e+00,
             4.90000000e+01, 4.90000000e+01], dtype=float32)

In [109]:
GGN_diagonal_by_stoch

tensor([[5.7374e-02, 8.9518e-02, 7.1054e-02, 2.9282e-01, 4.5687e-01, 3.6263e-01,
         8.8805e-02, 4.5323e-01, 1.3298e-01, 1.2826e-01, 1.3298e-01, 1.2826e-01,
         1.0000e+00, 1.0000e+00],
        [5.4939e-02, 3.3170e-01, 1.8270e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         8.8805e-02, 0.0000e+00, 6.6591e-01, 0.0000e+00, 6.6591e-01, 0.0000e+00,
         1.0000e+00, 1.0000e+00],
        [1.0542e-01, 1.3857e-03, 2.6079e-02, 5.3803e-01, 7.0722e-03, 1.3310e-01,
         8.8805e-02, 4.5323e-01, 3.9640e-02, 1.6969e-01, 3.9640e-02, 1.6969e-01,
         1.0000e+00, 1.0000e+00],
        [6.5552e-05, 2.9040e-03, 1.6457e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         8.8805e-02, 0.0000e+00, 2.7880e-01, 0.0000e+00, 2.7880e-01, 0.0000e+00,
         1.0000e+00, 1.0000e+00],
        [7.1358e-03, 6.8865e-02, 1.7081e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         8.8805e-02, 0.0000e+00, 8.4231e-02, 0.0000e+00, 8.4231e-02, 0.0000e+00,
         1.0000e+00, 1.0000e+00],
        [0.0000e+00,

In [108]:
GGN_diagonal_by_stoch2[0]

tensor([0.0574, 0.0895, 0.0711, 0.2928, 0.4569, 0.3626, 0.0888, 0.4532, 0.1330,
        0.1283, 0.1330, 0.1283, 1.0000, 1.0000], grad_fn=<SelectBackward0>)